-- ============================================================================
-- DebtType naming fix: RECURRING was overloaded for two different concepts
-- ============================================================================
--
-- The "D3 — installments" feature (register-installment-debt.use-case.ts)
-- reused DebtType.RECURRING to mark every row generated by splitting a debt
-- into N fixed installments — a finite series, not an open-ended recurrence.
-- That collided with the actual "Dívidas recorrentes" backlog item (a bill
-- that repeats indefinitely, e.g. rent, internet), which needs its own type
-- so PayDebtUseCase can tell them apart when deciding whether to auto-create
-- the next occurrence on payment.
--
-- Fix: rename the existing enum value to what it actually represents
-- (INSTALLMENT), then reintroduce RECURRING with its correct, original
-- meaning. RENAME VALUE only changes the catalog label — it does not touch
-- any existing row, so every already-created installment debt keeps working
-- unchanged, just reading as INSTALLMENT instead of RECURRING.
-- ============================================================================

ALTER TYPE "DebtType" RENAME VALUE 'RECURRING' TO 'INSTALLMENT';
ALTER TYPE "DebtType" ADD VALUE 'RECURRING';

-- ============================================================================
-- New ExpenseCategory: "Cartão de Crédito"
-- ============================================================================
--
-- Backfill for every existing user that doesn't have it yet (idempotent via
-- NOT EXISTS, safe to reason about even though this migration only ever runs
-- once per database).
-- ============================================================================

INSERT INTO "expense_categories" ("id", "user_id", "name", "slug", "is_active", "created_at", "updated_at")
SELECT gen_random_uuid(), "id", 'Cartão de Crédito', 'cartao-credito', true, NOW(), NOW()
FROM "users"
WHERE NOT EXISTS (
  SELECT 1 FROM "expense_categories"
  WHERE "expense_categories"."user_id" = "users"."id"
    AND "expense_categories"."slug" = 'cartao-credito'
);

-- Keep the user-provisioning trigger (see *_add_user_provisioning_trigger)
-- in sync so any future user also gets this 27th category.
CREATE OR REPLACE FUNCTION provision_default_user_data()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO "wallets" (
    "id", "user_id", "name", "is_default",
    "bank_balance", "cash_balance", "receivable_balance",
    "created_at", "updated_at"
  ) VALUES (
    gen_random_uuid(), NEW."id", 'Main Wallet', true,
    0, 0, 0,
    NOW(), NOW()
  );

  INSERT INTO "expense_categories" (
    "id", "user_id", "name", "slug", "is_active", "created_at", "updated_at"
  ) VALUES
    (gen_random_uuid(), NEW."id", 'Combustível', 'combustivel', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Alimentação', 'alimentacao', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Manutenção', 'manutencao', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Transporte', 'transporte', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Moradia / Aluguel', 'moradia-aluguel', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Energia', 'energia', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Água', 'agua', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Internet / Telefone', 'internet-telefone', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Compras / Insumos', 'compras-insumos', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Taxas / Impostos', 'taxas-impostos', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Equipamentos', 'equipamentos', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Marketing', 'marketing', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Saúde', 'saude', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Parcelas', 'parcelas', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Bebida alcoólica', 'bebida-alcoolica', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Bebida não alcoólica', 'bebida-nao-alcoolica', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Empréstimo pessoal', 'emprestimo-pessoal', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Assinaturas', 'assinaturas', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Seguros', 'seguros', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Cuidados pessoais', 'cuidados-pessoais', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Pet', 'pet', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Lazer / Entretenimento', 'lazer-entretenimento', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Vestuário', 'vestuario', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Educação', 'educacao', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Presentes', 'presentes', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Cartão de Crédito', 'cartao-credito', true, NOW(), NOW()),
    (gen_random_uuid(), NEW."id", 'Outros', 'outros', true, NOW(), NOW());

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
