@baseUrl = http://localhost:3000
@contentType = application/json

@authToken = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFkbWluQGZpbmFuY2Vjb250cm9sLmNvbSIsInN1YiI6IjQ3YTExZjNiLTQ0MDItNDRhMi05NjBkLTU0YmViNDZjZTlhMyIsImlhdCI6MTc3NzA4NTIwMywiZXhwIjoxNzc3NjkwMDAzfQ.cDxZeLZ4758H_xHIKFPZMGRH9QquptczkJVTH94oeqc

###
# @name getWallet
GET {{baseUrl}}/api/wallet
Cookie: Cookie: fc_access_token={{authToken}}

###
# @name updateWallet
PUT {{baseUrl}}/api/wallet
Content-Type: {{contentType}}
Cookie: Cookie: fc_access_token={{authToken}}

{
  "bankBalance": 1500,
  "cashBalance": 200,
  "receivableBalance": 450
}

###
# @name getWalletAfterUpdate
GET {{baseUrl}}/api/wallet
Cookie: Cookie: fc_access_token={{authToken}}

###
# @name getWalletSummary
GET {{baseUrl}}/api/wallet/summary
Cookie: Cookie: fc_access_token={{authToken}}

###
# @name updateWalletInvalid
PUT {{baseUrl}}/api/wallet
Content-Type: {{contentType}}
Cookie: Cookie: fc_access_token={{authToken}}

{
  "bankBalance": -1,
  "cashBalance": 200,
  "receivableBalance": 450
}

###
# @name getWalletUnauthorized
GET {{baseUrl}}/api/wallet